import type { Dispatch, SetStateAction } from "react";
import type { AdminMatchRecord, AuditLogEntry } from "@/types";
import type { AdminMatchFilters } from "@/hooks/useAdminMatchFilters";

export type Setter<T> = Dispatch<SetStateAction<T>>;

export type AdminMatchesPanelProps = {
  knockoutMatches: AdminMatchRecord[];
  knockoutReleased: boolean;
  setKnockoutReleasedPending: boolean;
  knockoutReleasedLoading: boolean;
  onToggleKnockout: () => void | Promise<void>;
  matchFilters: AdminMatchFilters;
  setMatchFilters: Setter<AdminMatchFilters>;
  phaseOptions: string[];
  groupOptions: string[];
  visibleMatches: AdminMatchRecord[];
  hasActiveMatchFilters: boolean;
  selectedMatchId: string;
  setSelectedMatchId: Setter<string>;
  selectedMatch: AdminMatchRecord | null;
  auditEntries: AuditLogEntry[] | undefined;
  resultHome: string;
  setResultHome: Setter<string>;
  resultAway: string;
  setResultAway: Setter<string>;
  penHome: string;
  setPenHome: Setter<string>;
  penAway: string;
  setPenAway: Setter<string>;
  newMatchHome: string;
  setNewMatchHome: Setter<string>;
  newMatchAway: string;
  setNewMatchAway: Setter<string>;
  newMatchPhase: string;
  setNewMatchPhase: Setter<string>;
  newMatchDate: string;
  setNewMatchDate: Setter<string>;
  newMatchTime: string;
  setNewMatchTime: Setter<string>;
  createMatchError: string;
  createMatchSuccess: string;
  showCreateMatchForm: boolean;
  setShowCreateMatchForm: Setter<boolean>;
  setCreateMatchError: Setter<string>;
  knockoutToggleMsg: string;
  editHome: string;
  setEditHome: Setter<string>;
  editAway: string;
  setEditAway: Setter<string>;
  editPhase: string;
  setEditPhase: Setter<string>;
  editMatchDate: string;
  setEditMatchDate: Setter<string>;
  editMatchTime: string;
  setEditMatchTime: Setter<string>;
  scheduleError: string;
  onCreateMatch: () => void | Promise<void>;
  createMatchPending: boolean;
  onToggleFinished: () => void | Promise<void>;
  onSaveResult: () => void | Promise<void>;
  onRecalculate: () => void | Promise<unknown>;
  onUpdateSchedule: () => void | Promise<void>;
  updateSchedulePending: boolean;
  onDeleteMatch: () => void | Promise<void>;
  deleteMatchPending: boolean;
};
