#[cfg(feature = "server")]
#[derive(sqlx::FromRow)]
pub(crate) struct QuestionRow {
    pub(crate) item_id: String,
    pub(crate) kind: String,
    pub(crate) title: String,
    pub(crate) lock_at: String,
    pub(crate) reveal_at: String,
    pub(crate) sort_order: i64,
    pub(crate) stored_status: String,
    pub(crate) current_option_id: Option<String>,
    pub(crate) correct_option_id: Option<String>,
    pub(crate) decimal_places: Option<i64>,
    pub(crate) unit_label: Option<String>,
    pub(crate) min_scaled: Option<i64>,
    pub(crate) max_scaled: Option<i64>,
    pub(crate) current_scaled: Option<i64>,
    pub(crate) result_scaled: Option<i64>,
    pub(crate) result_status: Option<String>,
    pub(crate) correct_points: Option<i64>,
    pub(crate) incorrect_points: Option<i64>,
    pub(crate) exact_points: Option<i64>,
    pub(crate) tolerance_scaled: Option<i64>,
    pub(crate) within_tolerance_points: Option<i64>,
    pub(crate) min_selections: Option<i64>,
    pub(crate) max_selections: Option<i64>,
    pub(crate) multiple_exact_points: Option<i64>,
    pub(crate) partial_points: Option<i64>,
    pub(crate) multiple_incorrect_points: Option<i64>,
    pub(crate) multiple_resolved: i64,
}
