import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { NumericPredictionCard } from "./NumericPredictionCard";
import { useCustomQuestions } from "@/hooks/queries";
import { setCsrfToken } from "@/lib/api";
import type { CustomQuestion } from "@/types";

const question: CustomQuestion = { itemId:"numeric-a",kind:"numeric",title:"Quantos prêmios?",lockAt:"2099-01-01T00:00:00Z",revealAt:"2099-01-02T00:00:00Z",sortOrder:0,status:"open",currentOptionId:null,correctOptionId:null,correctPoints:0,incorrectPoints:0,options:[],decimalPlaces:2,unitLabel:"prêmios",minValue:"0.00",maxValue:"20.00",currentValue:"12.34",exactPoints:5,tolerance:"1.00",withinTolerancePoints:2 };
function renderCard(overrides:Partial<CustomQuestion>={}){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><NumericPredictionCard question={{...question,...overrides}} poolId="pool-a" index={0}/></QueryClientProvider>);}
function ProgressHarness(){const {data:questions=[]}=useCustomQuestions("pool-a");const answered=questions.filter(item=>item.kind==="numeric"?item.currentValue!=null:item.currentOptionId!=null).length;const numeric=questions.find(item=>item.itemId==="numeric-a");return <><p>{answered} de {questions.length} categorias respondidas</p>{numeric&&<NumericPredictionCard question={numeric} poolId="pool-a" index={0}/>}</>;}
afterEach(()=>{vi.unstubAllGlobals();setCsrfToken(null);});
it("shows saved exact decimal value and unit",()=>{renderCard();expect((screen.getByRole("textbox",{name:"Valor para Quantos prêmios?"}) as HTMLInputElement).value).toBe("12.34");expect(screen.getByText(/unidade: prêmios/)).toBeTruthy();});
it("submits a decimal string without float conversion",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({csrfToken:"csrf"}))).mockResolvedValueOnce(new Response(null,{status:204}));vi.stubGlobal("fetch",fetchMock);renderCard({currentValue:null});const input=screen.getByRole("textbox",{name:"Valor para Quantos prêmios?"});fireEvent.change(input,{target:{value:"12.34"}});fireEvent.blur(input);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));expect(JSON.parse(fetchMock.mock.calls[1][1].body)).toEqual({poolId:"pool-a",itemId:"numeric-a",value:"12.34"});});
it("locks numeric input",()=>{renderCard({status:"locked"});expect((screen.getByRole("textbox",{name:"Valor para Quantos prêmios?"}) as HTMLInputElement).disabled).toBe(true);});
it("updates progress immediately once and keeps it stable on numeric edits",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({csrfToken:"csrf"}))).mockResolvedValue(new Response(null,{status:204}));vi.stubGlobal("fetch",fetchMock);const client=new QueryClient({defaultOptions:{queries:{retry:false,staleTime:Infinity},mutations:{retry:false}}});client.setQueryData<CustomQuestion[]>(["custom-questions","pool-a"],[{...question,currentValue:null},{...question,itemId:"choice-b",kind:"single_choice",title:"Escolha",currentOptionId:null,currentValue:null}]);render(<QueryClientProvider client={client}><ProgressHarness/></QueryClientProvider>);expect(screen.getByText("0 de 2 categorias respondidas")).toBeTruthy();const input=screen.getByRole("textbox",{name:"Valor para Quantos prêmios?"});fireEvent.change(input,{target:{value:"7"}});fireEvent.blur(input);await waitFor(()=>expect(screen.getByText("1 de 2 categorias respondidas")).toBeTruthy());fireEvent.change(input,{target:{value:"9"}});fireEvent.blur(input);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));expect(screen.getByText("1 de 2 categorias respondidas")).toBeTruthy();});
